name: First_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: test more lines
        run: |
          echo "First handson workflow"
          echo "Second test"
      
